name: Python Application Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.12' 

      - name: Run tests
        run: |
          pytest ./tests  # Aponte para o diretório de testes, caso esteja em uma pasta 'tests'
