name: Python Application Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Checar o código
      - name: Checkout code
        uses: actions/checkout@v3

      # Passo 2: Configurar o Python
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.12'  # Ajuste para a versão que você está usando

      # Passo 3: Instalar dependências
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Instala todas as dependências do seu projeto

      # Passo 4: Rodar os testes com pytest
      - name: Run tests
        run: |
          pytest ./tests  # Aponte para o diretório de testes, caso esteja em uma pasta 'tests'
